### Good request
POST http://localhost:8080/app/number/create/account
Content-Type: application/json

{
  "accountNumberLong":  "123",
  "accountNumberNullable": "123",
  "accountNumber": "123",
  "accountNumberEven": "123",
  "accountNumberOdd": "123"
}

### Failing request
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberNullable": "123",
  "accountNumber": "123",
  "accountNumberEven": "123",
  "accountNumberOdd": "123"
}

### Failing request
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberNullable": "123",
  "accountNumber": "123",
  "accountNumberEven": "123",
  "accountNumberOdd": "123"
}
