### Good request
POST http://localhost:8080/app/number/create/account
Content-Type: application/json

{
  "accountNumberLong":  "123",
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123"
}
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for null
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumberLong Null value
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123"
}

### Failing request accountNumberLong Null value
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123"
}

### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for positive numbers
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumberPositive is negative
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": -123
}

### Failing request accountNumberPositive is negative
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": -123
}

### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for negative numbers
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumberNegative is positive
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": 123
}

### Failing request accountNumberNegative is positive
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": 123
}

### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for even numbers
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumberEven is Odd
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "123",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123
}

### Failing request accountNumberEven is Odd
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "123",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123
}

### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for odd numbers
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumberOdd is Even
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "122",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123
}

### Failing request accountNumberOdd is Even
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": "7",
  "accountNumberEven": "122",
  "accountNumberOdd": "122",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123
}

### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for minimum numbers
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumber is under 5
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": 4.9,
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123
}

### Failing request accountNumber is under 5
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": 4.9,
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123
}

### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
### --->>> All fail tests for maximum numbers
### --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

### Failing request accountNumberMaxList is over 25
POST http://localhost:8080/app/number/create/account/programmatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": 5,
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123,
  "accountNumberMaxList": 26
}

### Failing request accountNumberMaxList is over 25
POST http://localhost:8080/app/number/create/account/automatic
Content-Type: application/json

{
  "accountNumberLong": 0,
  "accountNumberNullable": "123",
  "accountNumber": 5,
  "accountNumberEven": "122",
  "accountNumberOdd": "123",
  "accountNumberPositive": 123,
  "accountNumberNegative": -123,
  "accountNumberMaxList": 26
}
