 services:

  adopt-health-1:
    build: .
    entrypoint: java -jar ~/docker-boxing-health.jar && tail -f /dev/null
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "http://0.0.0.0:8080/health"]
      interval: 1s
      retries: 40
      start_period: 0s
      timeout: 20s

  adopt-health-2:
    build: .
    entrypoint: java -jar ~/docker-boxing-health.jar && tail -f /dev/null
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "http://0.0.0.0:8080/health"]
      interval: 1s
      retries: 40
      start_period: 0s
      timeout: 20s
