###
POST http://localhost:8080/fix/users
Content-Type: application/json

{
  "name": "Joao",
  "receipts": [],
  "shops": []
}

###
GET http://localhost:8080/bad/users/all
###
GET http://localhost:8080/badfix/users/all
###
GET http://localhost:8080/fix/users/all
