DROP TABLE IF EXISTS BAD_DISLIKES_RELATIONS;

CREATE TABLE IF NOT EXISTS BAD_DISLIKES_RELATIONS
(
    id IDENTITY NOT NULL PRIMARY KEY,
    user_id   INT NOT NULL,
    shop_id   INT NOT NULL,
    receipt_id   INT NOT NULL
);
